# Generated by Django 2.2.6 on 2020-05-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_templates',
            field=models.ManyToManyField(blank=True, to='web.SurveyTemplate', verbose_name='针对哪几个角色的问卷调查'),
        ),
    ]
