# Generated by Django 2.2.6 on 2020-05-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200512_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveychoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='web.SurveyQuestion', verbose_name='关联问题'),
        ),
        migrations.AlterField(
            model_name='surveyrecord',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.SurveyQuestion', verbose_name='哪一个问题'),
        ),
        migrations.AlterField(
            model_name='surveyrecord',
            name='survey_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.SurveyTemplate', verbose_name='哪一个角色的'),
        ),
    ]
