# Generated by Django 2.2.6 on 2020-05-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200521_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
