# Generated by Django 2.2.6 on 2020-05-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_survey_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='created',
            field=models.BooleanField(default=True),
        ),
    ]
